"use client";

import { useEffect, useRef, useState } from "react";
import { LogoBlanco } from "@/components/marca/Logo";

type Aporte = { id: string; nombre: string; empresaId: string; empresa: string; texto: string; planetaId: string; planeta: string; color: string; fecha: string };
type Datos = { aportes: Aporte[]; cifras: { aportes: number; personas: number; empresas: number }; ahora: string };
type EstrellaAporte = Aporte & { x: number; y: number; z: number; escala: number; magnitud: number; fase: number; nacida: number };

function hash(texto: string) { let valor = 2166136261; for (let i = 0; i < texto.length; i += 1) { valor ^= texto.charCodeAt(i); valor = Math.imul(valor, 16777619); } return valor >>> 0; }
function rng(semilla: number) { let valor = semilla || 1; return () => { valor = Math.imul(valor ^ valor >>> 15, 1 | valor); valor ^= valor + Math.imul(valor ^ valor >>> 7, 61 | valor); return ((valor ^ valor >>> 14) >>> 0) / 4294967296; }; }
function gauss(azar: () => number) { return Math.sqrt(-2 * Math.log(Math.max(azar(), 1e-7))) * Math.cos(2 * Math.PI * azar()); }
function rgba(hex: string, alfa: number) { const limpio = hex.replace("#", ""); const valor = Number.parseInt(limpio.length === 3 ? limpio.split("").map((x) => x + x).join("") : limpio, 16); return `rgba(${valor >> 16},${valor >> 8 & 255},${valor & 255},${alfa})`; }

function posicionAporte(aporte: Aporte): EstrellaAporte {
  const azar = rng(hash(aporte.id)); let radio: number; let angulo: number;
  if (azar() < .55) { const theta = Math.pow(azar(), .85) * 4; radio = .05 * Math.exp(.72 * theta); angulo = theta + (azar() < .5 ? 0 : Math.PI) + gauss(azar) * (.26 * (.55 + .7 * (1 - radio)) + .55); }
  else { radio = .1 + Math.pow(azar(), .72) * .87; angulo = azar() * Math.PI * 2; }
  radio = Math.max(.1, Math.min(.97, radio * (1 + (azar() - .5) * .36)));
  return { ...aporte, x: Math.cos(angulo) * radio, y: Math.sin(angulo) * radio, z: gauss(azar) * .05, escala: .55 + azar() * .75, magnitud: .45 + azar() * .55, fase: azar() * Math.PI * 2, nacida: performance.now() };
}

function construirDisco(radio: number) {
  const canvas = document.createElement("canvas"); const lado = Math.ceil(radio * 2); canvas.width = lado; canvas.height = lado; const ctx = canvas.getContext("2d")!; const centro = lado / 2; const azar = rng(731905);
  ctx.globalCompositeOperation = "lighter";
  const puntoBrazo = (extra = 0) => { const theta = Math.pow(azar(), .85) * 4; let r = .05 * Math.exp(.72 * theta); const dispersion = gauss(azar) * (.26 * (.55 + .7 * (1 - r)) + extra); const angulo = theta + (azar() < .5 ? 0 : Math.PI) + dispersion; r *= 1 + gauss(azar) * .1; return { x: centro + Math.cos(angulo) * r * radio, y: centro + Math.sin(angulo) * r * radio, r }; };
  const tintes = [[30,90,170],[20,120,130],[80,50,150],[70,120,60]];
  for (let i = 0; i < 95; i += 1) { const p = puntoBrazo(.2); const tamano = (.05 + azar() * .14) * radio; const t = tintes[i % tintes.length]; const g = ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,tamano); g.addColorStop(0,`rgba(${t[0]},${t[1]},${t[2]},${.10 + azar() * .13})`); g.addColorStop(1,`rgba(${t[0]},${t[1]},${t[2]},0)`); ctx.fillStyle=g;ctx.fillRect(p.x-tamano,p.y-tamano,tamano*2,tamano*2); }
  const bulbo = ctx.createRadialGradient(centro,centro,0,centro,centro,.36*radio); bulbo.addColorStop(0,"rgba(255,246,222,.92)");bulbo.addColorStop(.22,"rgba(255,215,152,.42)");bulbo.addColorStop(.55,"rgba(190,150,120,.13)");bulbo.addColorStop(1,"transparent");ctx.fillStyle=bulbo;ctx.fillRect(centro-radio,centro-radio,radio*2,radio*2);
  const colores = ["255,255,255","206,226,255","255,230,195","255,198,165","195,224,90","120,220,205"];
  for (let i = 0; i < 4200; i += 1) { let p; if (azar() < .74) p = puntoBrazo(0); else { const r = Math.pow(azar(),1.9); const a=azar()*Math.PI*2;p={x:centro+Math.cos(a)*r*radio,y:centro+Math.sin(a)*r*radio,r}; } const gigante=azar()<.03; const tamano=gigante?.8+azar()*2:.35+azar()*.8; const color=azar()<.14?colores[2+Math.floor(azar()*4)]:colores[Math.floor(azar()*2)]; ctx.fillStyle=`rgba(${color},${(.35+azar()*.6)*(1-.4*p.r)})`;ctx.beginPath();ctx.arc(p.x,p.y,tamano,0,Math.PI*2);ctx.fill(); }
  ctx.globalCompositeOperation="destination-out";
  for(let i=0;i<190;i+=1){const theta=Math.pow(azar(),.85)*4;const r=.05*Math.exp(.72*theta);const a=theta+(azar()<.5?0:Math.PI)+.32+gauss(azar)*.2;const x=centro+Math.cos(a)*r*radio,y=centro+Math.sin(a)*r*radio,t=(.02+azar()*.07)*radio;const g=ctx.createRadialGradient(x,y,0,x,y,t);g.addColorStop(0,`rgba(0,0,0,${.18+azar()*.26})`);g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(x-t,y-t,t*2,t*2);}
  const vineta=ctx.createRadialGradient(centro,centro,.42*radio,centro,centro,radio);vineta.addColorStop(0,"rgba(0,0,0,0)");vineta.addColorStop(.052,"rgba(0,0,0,.18)");vineta.addColorStop(.517,"rgba(0,0,0,.62)");vineta.addColorStop(.828,"rgba(0,0,0,.93)");vineta.addColorStop(1,"rgba(0,0,0,1)");ctx.fillStyle=vineta;ctx.fillRect(0,0,lado,lado); return canvas;
}

function dibujarEstrella(ctx: CanvasRenderingContext2D, estrella: EstrellaAporte, x: number, y: number, dpr: number, ahora: number) {
  const titileo = 1 + Math.sin(ahora * .003 + estrella.fase) * .18; const r = (.85 + estrella.escala * .7) * dpr * titileo; const edad = Math.min(1, (ahora - estrella.nacida) / 1100); const haloR = r * (11 + (1 - edad) * 16);
  const halo=ctx.createRadialGradient(x,y,0,x,y,haloR);halo.addColorStop(0,rgba(estrella.color,.25*edad));halo.addColorStop(.3,rgba(estrella.color,.09*edad));halo.addColorStop(1,"transparent");ctx.fillStyle=halo;ctx.fillRect(x-haloR,y-haloR,haloR*2,haloR*2);
  const bloomR=r*3.4;const bloom=ctx.createRadialGradient(x,y,0,x,y,bloomR);bloom.addColorStop(0,`rgba(255,255,255,${.85*edad})`);bloom.addColorStop(.24,`rgba(255,255,255,${.3*edad})`);bloom.addColorStop(.55,rgba(estrella.color,.16*edad));bloom.addColorStop(1,"transparent");ctx.fillStyle=bloom;ctx.fillRect(x-bloomR,y-bloomR,bloomR*2,bloomR*2);
  const largo=r*(3.8+estrella.escala*1.8); const destello=(x1:number,y1:number,x2:number,y2:number,alfa:number)=>{const g=ctx.createLinearGradient(x1,y1,x2,y2);g.addColorStop(0,"transparent");g.addColorStop(.5,`rgba(255,255,255,${alfa*edad})`);g.addColorStop(1,"transparent");ctx.strokeStyle=g;ctx.lineWidth=Math.max(.35*dpr,r*.17);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();};destello(x-largo,y,x+largo,y,.16);destello(x,y-largo*.62,x,y+largo*.62,.12);
  ctx.fillStyle=`rgba(255,255,255,${edad})`;ctx.beginPath();ctx.arc(x,y,r*.95,0,Math.PI*2);ctx.fill(); if(edad<1){ctx.strokeStyle=rgba(estrella.color,(1-edad)*(edad*edad)*.6);ctx.lineWidth=1.2*dpr;ctx.beginPath();ctx.arc(x,y,r*(6+edad*34),0,Math.PI*2);ctx.stroke();}
}

export function GalaxiaColectiva({ demo = false }: { demo?: boolean }) {
  const canvasRef=useRef<HTMLCanvasElement>(null); const estrellasRef=useRef<EstrellaAporte[]>([]); const idsRef=useRef(new Set<string>()); const [ultimo,setUltimo]=useState<Aporte|null>(null); const [cifras,setCifras]=useState({aportes:0,personas:0,empresas:0});
  // Se conserva para cancelar el sondeo cuando la proyección se desmonta.
  // eslint-disable-next-line prefer-const
  useEffect(()=>{let cancelado=false;let intervalo:number|undefined;let ultimoInstante="";let demoIndice=0;const ejemplos=[{nombre:"Ana María",empresa:"EPM",empresaId:"epm",texto:"Voy a escuchar la emoción antes de proponer una solución.",planetaId:"cliente",planeta:"El Cliente",color:"#3FD6A8"},{nombre:"Carlos",empresa:"CENS",empresaId:"cens",texto:"Haré visible el siguiente paso para reducir la incertidumbre.",planetaId:"viaje",planeta:"El Viaje",color:"#6FB6FF"},{nombre:"Sofía",empresa:"CHEC",empresaId:"chec",texto:"Convertiré una frontera interna en un puente entre equipos.",planetaId:"rol",planeta:"Nuestro Rol",color:"#C77BFF"}];const agregar=(aporte:Aporte)=>{if(idsRef.current.has(aporte.id))return;idsRef.current.add(aporte.id);const estrella=posicionAporte(aporte);estrellasRef.current.push(estrella);setUltimo(aporte);};const cargar=async(inicial=false)=>{try{const respuesta=await fetch(`/api/universo/galaxia${inicial?"":`?desde=${encodeURIComponent(ultimoInstante)}`}`,{cache:"no-store"});if(!respuesta.ok)return;const datos=await respuesta.json() as Datos;if(!demo)setCifras(datos.cifras);ultimoInstante=datos.ahora;if(inicial&&!demo){datos.aportes.forEach((aporte,indice)=>window.setTimeout(()=>{if(!cancelado)agregar(aporte);},indice*380));}else if(!demo)datos.aportes.forEach(agregar);}catch{}};void cargar(true);intervalo=window.setInterval(()=>void cargar(false),2200);let demoTimer:number|undefined;if(demo){const simular=()=>{const base=ejemplos[demoIndice%ejemplos.length];demoIndice+=1;const aporte={...base,id:`demo-${Date.now()}-${demoIndice}`,fecha:new Date().toISOString()};agregar(aporte);setCifras({aportes:demoIndice,personas:demoIndice,empresas:Math.min(ejemplos.length,demoIndice)});};simular();demoTimer=window.setInterval(simular,5200);}return()=>{cancelado=true;if(intervalo)clearInterval(intervalo);if(demoTimer)clearInterval(demoTimer);};},[demo]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d")!;let ancho=0,alto=0,dpr=1,radio=0,disco:HTMLCanvasElement,campo:{x:number;y:number;r:number;a:number}[]=[];let cuadro=0;let resizeTimer:number;const preparar=()=>{const rect=canvas.getBoundingClientRect();dpr=Math.min(window.devicePixelRatio||1,1.5);ancho=Math.round(rect.width*dpr);alto=Math.round(rect.height*dpr);canvas.width=ancho;canvas.height=alto;radio=Math.min(1300,Math.min(ancho*.46,alto*.92));disco=construirDisco(radio);const azar=rng(98731);campo=Array.from({length:420},()=>({x:azar()*ancho,y:azar()*alto,r:(.35+azar()*1.15)*dpr,a:.18+azar()*.62}));};preparar();const alResize=()=>{clearTimeout(resizeTimer);resizeTimer=window.setTimeout(preparar,300);};window.addEventListener("resize",alResize);const reducido=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const dibujar=(ahora:number)=>{ctx.globalCompositeOperation="source-over";ctx.fillStyle="#02060E";ctx.fillRect(0,0,ancho,alto);ctx.fillStyle="#fff";for(const e of campo){ctx.globalAlpha=e.a;ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;const angulo=reducido?0:ahora*.000022;ctx.save();ctx.translate(ancho/2,alto/2);ctx.rotate(angulo);ctx.scale(1,.5);ctx.globalCompositeOperation="lighter";ctx.drawImage(disco,-radio,-radio,radio*2,radio*2);ctx.restore();const proyectadas=estrellasRef.current.map((e)=>{const cos=Math.cos(angulo),sin=Math.sin(angulo);return{e,x:ancho/2+(e.x*cos-e.y*sin)*radio,y:alto/2+(e.x*sin+e.y*cos)*radio*.5+e.z*radio};});ctx.globalCompositeOperation="lighter";const limite=.17*Math.min(ancho,alto);for(let i=0;i<proyectadas.length;i+=1){const actual=proyectadas[i];let cercana:null|typeof actual=null,distancia=Infinity;for(let j=0;j<proyectadas.length;j+=1){if(i===j||proyectadas[j].e.empresaId!==actual.e.empresaId)continue;const d=Math.hypot(proyectadas[j].x-actual.x,proyectadas[j].y-actual.y);if(d<distancia){distancia=d;cercana=proyectadas[j];}}if(cercana&&distancia<limite){ctx.strokeStyle=`rgba(195,224,90,${.09*(1-distancia/limite)})`;ctx.lineWidth=.65*dpr;ctx.beginPath();ctx.moveTo(actual.x,actual.y);ctx.lineTo(cercana.x,cercana.y);ctx.stroke();}}for(const p of proyectadas)dibujarEstrella(ctx,p.e,p.x,p.y,dpr,ahora);cuadro=requestAnimationFrame(dibujar);};cuadro=requestAnimationFrame(dibujar);return()=>{cancelAnimationFrame(cuadro);clearTimeout(resizeTimer);window.removeEventListener("resize",alResize);};},[]);
  useEffect(()=>{if(!ultimo)return;const timer=window.setTimeout(()=>setUltimo(null),4200);return()=>clearTimeout(timer);},[ultimo]);
  return <main className="galaxia-ui fixed inset-0 overflow-hidden bg-[#02060E] text-[#EAF2F8]"><canvas ref={canvasRef} className="absolute inset-0 h-full w-full" /><header className="absolute left-6 top-6 z-10 max-w-[340px] max-[520px]:top-24 sm:left-10 sm:top-9"><h1 className="text-[clamp(27px,3vw,44px)] font-normal tracking-tight">Galaxia <strong>colectiva</strong></h1><p className="mt-2 text-sm leading-relaxed text-[rgba(234,242,248,.62)] sm:text-base">Cada estrella es el aporte de una persona del Grupo</p></header><LogoBlanco className="absolute right-6 top-6 z-10 h-auto w-[clamp(130px,14vw,210px)] sm:right-10 sm:top-9" /><aside className="absolute bottom-6 right-6 z-10 space-y-1 text-right sm:bottom-9 sm:right-10">{[[cifras.aportes,"APORTES"],[cifras.personas,"PERSONAS"],[cifras.empresas,"EMPRESAS"]].map(([numero,etiqueta])=><div key={String(etiqueta)} className="flex items-baseline justify-end gap-3"><strong className="text-[clamp(27px,4vw,48px)] font-bold leading-none text-[#C3E05A]">{numero}</strong><span className="w-24 text-left text-[10px] font-bold tracking-[2px] text-white/55 sm:text-xs">{etiqueta}</span></div>)}</aside>{ultimo&&<section key={ultimo.id} className="aporte-ultimo absolute bottom-7 left-1/2 z-10 w-[min(640px,54vw)] -translate-x-1/2 text-center max-[820px]:bottom-36 max-[820px]:w-[88%]"><blockquote className="text-[clamp(16px,2vw,24px)] font-semibold leading-relaxed">“{ultimo.texto}”</blockquote><p className="mt-2 text-[12.5px] font-bold uppercase tracking-[.14em] text-[#C3E05A]">{ultimo.nombre} · {ultimo.empresa}</p></section>}<style jsx>{`.galaxia-ui{font-family:var(--font-quicksand),sans-serif}.aporte-ultimo{animation:aporte-entra 4.2s ease both}@keyframes aporte-entra{0%{opacity:0;transform:translate(-50%,18px)}12%,82%{opacity:1;transform:translate(-50%,0)}100%{opacity:0;transform:translate(-50%,-5px)}}`}</style></main>;
}
