"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, CheckCircle2, LoaderCircle, Orbit, Send, Sparkles, X } from "lucide-react";
import type { PlanetaArquetipo, RetoUniverso } from "@/lib/universo-arquetipos";

export function RetosPlaneta({ planeta, retos, completadosIniciales }: { planeta: PlanetaArquetipo; retos: RetoUniverso[]; completadosIniciales: string[] }) {
  const [completados, setCompletados] = useState(new Set(completadosIniciales));
  const [retoActivo, setRetoActivo] = useState<RetoUniverso | null>(null);
  const [texto, setTexto] = useState(""); const [enviando, setEnviando] = useState(false); const [error, setError] = useState(""); const [puntos, setPuntos] = useState<number | null>(null);
  async function guardar() {
    if (!retoActivo || texto.trim().length < 12 || enviando) return;
    setEnviando(true); setError("");
    try { const respuesta = await fetch(`/api/universo/retos/${encodeURIComponent(retoActivo.id)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ texto: texto.trim() }) }); const cuerpo = await respuesta.json(); if (!respuesta.ok) throw new Error(cuerpo.error ?? "No pudimos guardar tu aporte."); setCompletados((actuales) => new Set([...actuales, retoActivo.id])); setPuntos(cuerpo.puntosOtorgados); setTexto(""); window.setTimeout(() => { setRetoActivo(null); setPuntos(null); }, 1300); } catch (e) { setError(e instanceof Error ? e.message : "No pudimos guardar tu aporte."); } finally { setEnviando(false); }
  }
  return <main className="mx-auto min-h-dvh max-w-6xl px-5 py-7 sm:px-8"><header className="flex items-start justify-between gap-4"><div><Link href="/universo" className="inline-flex items-center gap-2 text-sm font-extrabold text-cyan-100/65"><ArrowLeft size={18} /> Mapa estelar</Link><p className="mt-6 text-xs font-extrabold uppercase tracking-[.2em]" style={{ color: planeta.color }}>Planeta {planeta.numero}</p><h1 className="mt-2 font-display text-[clamp(38px,7vw,72px)] font-extrabold leading-none">{planeta.nombre}</h1><p className="mt-4 max-w-2xl text-lg leading-relaxed text-white/65">{planeta.lema}</p></div><span className="relative mt-8 hidden h-36 w-36 shrink-0 rounded-full sm:block" style={{ background: `radial-gradient(circle at 32% 26%,#fff 0 3%,${planeta.color} 12%,${planeta.colorProfundo} 65%,#030711)`, boxShadow: `0 0 55px ${planeta.color}55` }}><span className="absolute left-1/2 top-1/2 h-[26%] w-[145%] -translate-x-1/2 -translate-y-1/2 rotate-[-14deg] rounded-[50%] border-4 border-white/20" /></span></header>
    <section className="mt-9 grid gap-5 md:grid-cols-3">{retos.map((reto, indice) => { const completo = completados.has(reto.id); return <button key={reto.id} type="button" onClick={() => { if (!completo) { setRetoActivo(reto); setError(""); setPuntos(null); } }} className={`relative min-h-72 overflow-hidden rounded-[2rem] border p-6 text-left transition ${completo ? "border-lime-300/35 bg-lime-300/10" : "border-white/12 bg-white/[.07] hover:-translate-y-1 hover:border-white/30"}`}><span className="absolute -right-10 -top-10 h-32 w-32 rounded-full border-[16px] border-white/5" /><div className="relative flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/10 font-display text-xl font-extrabold">{indice + 1}</span>{completo ? <CheckCircle2 className="text-lime-300" /> : <Orbit style={{ color: planeta.color }} />}</div><h2 className="relative mt-14 font-display text-2xl font-extrabold">{reto.titulo}</h2><p className="relative mt-3 line-clamp-4 leading-relaxed text-white/62">{reto.consigna}</p><span className="relative mt-5 inline-flex rounded-full px-3 py-1.5 text-xs font-extrabold" style={{ background: `${planeta.color}22`, color: planeta.color }}>{completo ? "En la galaxia" : `${reto.puntos} puntos`}</span></button>; })}</section>
    {retoActivo && <div className="fixed inset-0 z-[80] grid place-items-center bg-[#02060e]/85 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="reto-titulo"><div className="w-full max-w-2xl rounded-[2rem] border border-white/15 bg-[#091c3a] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{ color: planeta.color }}>{planeta.nombre} · {retoActivo.puntos} puntos</p><h2 id="reto-titulo" className="mt-2 font-display text-3xl font-extrabold">{retoActivo.titulo}</h2></div><button type="button" onClick={() => setRetoActivo(null)} className="grid h-11 w-11 place-items-center rounded-full bg-white/10"><X /></button></div><p className="mt-5 text-xl font-bold leading-relaxed">{retoActivo.consigna}</p>{puntos !== null ? <div className="mt-6 rounded-2xl border border-lime-300/25 bg-lime-300/10 p-6 text-center"><Sparkles className="mx-auto text-lime-300" size={35} /><strong className="mt-3 block font-display text-2xl">Tu estrella ya brilla en la galaxia</strong>{puntos > 0 && <span className="mt-2 block font-extrabold text-lime-200">+{puntos} puntos</span>}</div> : <><label className="mt-6 block"><span className="text-sm font-extrabold text-cyan-100">Tu aporte en dos o tres frases</span><textarea data-testid="respuesta-reto-universo" value={texto} onChange={(evento) => setTexto(evento.target.value)} maxLength={800} className="mt-2 min-h-40 w-full rounded-2xl border border-white/15 bg-[#031027] p-4 text-white outline-none placeholder:text-white/30 focus:border-lime-300" placeholder="Escribe tu reflexión…" /></label><div className="mt-2 flex justify-between text-xs text-white/35"><span>Mínimo 12 caracteres</span><span>{texto.length}/800</span></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-400/10 p-3 font-bold text-red-100">{error}</p>}<button type="button" onClick={() => void guardar()} disabled={texto.trim().length < 12 || enviando} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-lime-300 px-5 py-3 font-display font-extrabold text-[#071a38] disabled:opacity-35">{enviando ? <LoaderCircle className="animate-spin" /> : <Send />} Enviar a la Galaxia Colectiva</button></>}</div></div>}
  </main>;
}
