"use client";

import Link from "next/link";
import { Download, Map, Orbit, Sparkles } from "lucide-react";
import type { PlanetaArquetipo } from "@/lib/universo-arquetipos";

export function TarjetaArquetipo({ planeta, ruta, revelar }: { planeta: PlanetaArquetipo; ruta: PlanetaArquetipo[]; revelar: boolean }) {
  function descargar() {
    const canvas = document.createElement("canvas"); canvas.width = 900; canvas.height = 1200;
    const ctx = canvas.getContext("2d"); if (!ctx) return;
    const fondo = ctx.createLinearGradient(0, 0, 900, 1200); fondo.addColorStop(0, planeta.colorProfundo); fondo.addColorStop(.55, "#071a38"); fondo.addColorStop(1, "#02060e"); ctx.fillStyle = fondo; ctx.fillRect(0, 0, 900, 1200);
    for (let i = 0; i < 90; i += 1) { const x = (i * 137) % 880 + 10; const y = (i * 223) % 1160 + 10; ctx.globalAlpha = .18 + i % 5 * .12; ctx.fillStyle = "#fff"; ctx.beginPath(); ctx.arc(x, y, 1 + i % 3, 0, Math.PI * 2); ctx.fill(); }
    ctx.globalAlpha = 1; const planetaGradiente = ctx.createRadialGradient(670, 115, 25, 670, 115, 285); planetaGradiente.addColorStop(0, "#fff"); planetaGradiente.addColorStop(.08, planeta.color); planetaGradiente.addColorStop(.62, planeta.colorProfundo); planetaGradiente.addColorStop(1, "#050817"); ctx.fillStyle = planetaGradiente; ctx.beginPath(); ctx.arc(720, 40, 310, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = "rgba(255,255,255,.13)"; ctx.roundRect(62, 80, 360, 62, 31); ctx.fill(); ctx.fillStyle = "#EAF2F8"; ctx.font = "700 26px Arial"; ctx.fillText(planeta.tema.toUpperCase(), 90, 121);
    ctx.font = "800 66px Arial"; const palabras = planeta.arquetipo.split(" "); let linea = ""; let y = 420; for (const palabra of palabras) { const prueba = `${linea}${palabra} `; if (ctx.measureText(prueba).width > 760 && linea) { ctx.fillText(linea.trim(), 66, y); linea = `${palabra} `; y += 76; } else linea = prueba; } ctx.fillText(linea.trim(), 66, y);
    ctx.fillStyle = "rgba(234,242,248,.82)"; ctx.font = "500 30px Arial"; const texto = planeta.descripcion.split(" "); linea = ""; y += 86; for (const palabra of texto) { const prueba = `${linea}${palabra} `; if (ctx.measureText(prueba).width > 760 && linea) { ctx.fillText(linea.trim(), 66, y); linea = `${palabra} `; y += 42; } else linea = prueba; } ctx.fillText(linea.trim(), 66, y);
    y += 92; ctx.fillStyle = planeta.color; ctx.font = "700 23px Arial"; ctx.fillText("TU RUTA SUGERIDA", 66, y); y += 46; ctx.fillStyle = "#EAF2F8"; ctx.font = "600 24px Arial"; ruta.forEach((item, indice) => { ctx.fillText(`${indice + 1}. ${item.nombre}`, 66 + (indice % 2) * 360, y + Math.floor(indice / 2) * 42); });
    ctx.fillStyle = "#fff"; ctx.font = "700 39px Arial"; ctx.fillText("Grupo·epm", 66, 1125);
    const enlace = document.createElement("a"); enlace.download = `mi-planeta-${planeta.id}.png`; enlace.href = canvas.toDataURL("image/png"); enlace.click();
  }

  return <main className="mx-auto flex min-h-dvh max-w-6xl flex-col items-center justify-center gap-7 px-5 py-8 lg:flex-row">
    <div className={`tarjeta-arquetipo h-[min(72vh,680px)] aspect-[3/4] ${revelar ? "revelar" : ""}`}><article className="cara-tarjeta relative h-full overflow-hidden rounded-[2.3rem] border border-white/20 p-7 shadow-[0_35px_100px_rgba(0,0,0,.55)] sm:p-9" style={{ background: `linear-gradient(155deg,${planeta.colorProfundo},#071a38 58%,#02060e)` }}><span className="absolute -right-24 -top-28 h-80 w-80 rounded-full" style={{ background: `radial-gradient(circle at 34% 30%,white 0 3%,${planeta.color} 12%,${planeta.colorProfundo} 62%,#030711 100%)`, boxShadow: `0 0 60px ${planeta.color}55` }} /><span className="relative inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-[.16em]">{planeta.tema}</span><div className="relative mt-[42%]"><p className="text-sm font-extrabold uppercase tracking-[.2em]" style={{ color: planeta.color }}>{planeta.nombre}</p><h1 className="mt-3 font-display text-[clamp(35px,5vw,54px)] font-extrabold leading-[.92]">{planeta.arquetipo}</h1><p className="mt-5 text-[clamp(15px,2vw,19px)] leading-relaxed text-white/78">{planeta.descripcion}</p><div className="mt-7 border-t border-white/15 pt-5"><p className="text-xs font-extrabold uppercase tracking-[.18em]" style={{ color: planeta.color }}>Tu ruta sugerida</p><div className="mt-3 flex flex-wrap gap-2">{ruta.map((item, indice) => <span key={item.id} className="rounded-full border border-white/15 bg-white/[.07] px-3 py-1.5 text-xs font-bold"><b style={{ color: item.color }}>{indice + 1}</b> · {item.nombre}</span>)}</div></div></div><strong className="absolute bottom-6 left-8 font-display text-xl">Grupo·epm</strong></article></div>
    <section className="w-full max-w-md rounded-[2rem] border border-white/12 bg-white/[.07] p-6 backdrop-blur"><div className="flex items-center gap-3 text-lime-300"><Sparkles /><p className="font-extrabold uppercase tracking-[.15em]">Tu arquetipo está listo</p></div><h2 className="mt-4 font-display text-3xl font-extrabold">Esta es tu forma natural de aportar.</h2><p className="mt-3 leading-relaxed text-white/65">Tu planeta es el punto de partida, no una etiqueta. Recorre los cinco mundos y convierte cada señal en una acción.</p><button type="button" onClick={descargar} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full border border-white/25 px-5 py-3 font-extrabold"><Download /> Descargar mi tarjeta</button><Link href="/universo" className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-full bg-lime-300 px-5 py-3 font-display font-extrabold text-[#071a38]"><Map /> Entrar al mapa estelar</Link><Link href={`/universo/planeta/${planeta.id}`} className="mt-3 inline-flex w-full items-center justify-center gap-2 text-sm font-extrabold text-cyan-100/65"><Orbit size={18} /> Comenzar por mi planeta</Link></section>
    <style jsx>{`.tarjeta-arquetipo{perspective:1400px}.cara-tarjeta{transform-origin:center;backface-visibility:hidden}.revelar .cara-tarjeta{animation:voltear 1.15s cubic-bezier(.2,.8,.2,1) both}@keyframes voltear{0%{opacity:0;transform:rotateY(180deg) scale(.78)}55%{opacity:1}100%{transform:rotateY(0) scale(1)}}`}</style>
  </main>;
}
