"use client";

import { useState } from "react";
import { Plus, Save, Sparkles, Trash2 } from "lucide-react";
import { guardarRetosUniverso } from "@/app/admin/(privado)/actividades/universo-actions";
import type { ConfiguracionUniversoArquetipos, PlanetaId, RetoUniverso } from "@/lib/universo-arquetipos";

export function EditorUniversoArquetipos({ actividadId, configuracion }: { actividadId: string; configuracion: ConfiguracionUniversoArquetipos }) {
  const [retos, setRetos] = useState(configuracion.retos);
  function actualizar(id: string, cambios: Partial<RetoUniverso>) { setRetos((actuales) => actuales.map((reto) => reto.id === id ? { ...reto, ...cambios } : reto)); }
  function agregar(planetaId: PlanetaId) { setRetos((actuales) => [...actuales, { id: `${planetaId}-${Date.now()}`, planetaId, titulo: "Nueva señal", consigna: "Escribe aquí una pregunta abierta para responder en dos o tres frases.", puntos: 20, orden: actuales.filter((reto) => reto.planetaId === planetaId).length + 1, activo: true }]); }
  function eliminar(id: string) { setRetos((actuales) => actuales.filter((reto) => reto.id !== id)); }
  const valor = { ...configuracion, retos };
  return <form action={guardarRetosUniverso} className="space-y-6"><input type="hidden" name="id" value={actividadId} /><input type="hidden" name="configuracion" value={JSON.stringify(valor)} />
    <div className="rounded-3xl border border-indigo-200 bg-gradient-to-br from-indigo-50 to-cyan-50 p-5"><div className="flex items-center gap-3"><Sparkles className="text-indigo-700" /><div><h2 className="text-xl font-extrabold text-[var(--epm-azul-profundo)]">Universo de arquetipos y retos</h2><p className="mt-1 text-slate-600">El test conserva cinco preguntas. Puedes crear, editar, desactivar o ajustar los puntos de los retos incluso durante el evento.</p></div></div></div>
    {configuracion.planetas.map((planeta) => { const retosPlaneta = retos.filter((reto) => reto.planetaId === planeta.id).sort((a,b)=>a.orden-b.orden); return <section key={planeta.id} className="tarjeta overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 p-5 text-white" style={{ background: `linear-gradient(120deg,${planeta.colorProfundo},${planeta.color})` }}><div><p className="text-xs font-extrabold uppercase tracking-[.18em]">Planeta {planeta.numero}</p><h2 className="font-display text-2xl font-extrabold">{planeta.nombre}</h2><p className="mt-1 text-sm text-white/80">{planeta.lema}</p></div><button type="button" onClick={() => agregar(planeta.id)} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 font-extrabold text-slate-800"><Plus size={18} /> Agregar reto</button></header><div className="space-y-4 p-5">{retosPlaneta.map((reto,indice)=><article key={reto.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-4 lg:grid-cols-[1fr_150px_120px_auto]"><label><span className="etiqueta">Título</span><input className="campo" value={reto.titulo} onChange={(e)=>actualizar(reto.id,{titulo:e.target.value})} /></label><label><span className="etiqueta">Puntos</span><input className="campo" type="number" min={0} max={1000} value={reto.puntos} onChange={(e)=>actualizar(reto.id,{puntos:Number(e.target.value)})} /></label><label><span className="etiqueta">Estado</span><select className="campo" value={String(reto.activo)} onChange={(e)=>actualizar(reto.id,{activo:e.target.value==="true"})}><option value="true">Activo</option><option value="false">Oculto</option></select></label><button type="button" onClick={()=>eliminar(reto.id)} className="mt-7 grid h-11 w-11 place-items-center rounded-full bg-red-50 text-red-700" aria-label={`Eliminar ${reto.titulo}`}><Trash2 size={18} /></button></div><label className="mt-4 block"><span className="etiqueta">Consigna abierta</span><textarea className="campo min-h-28" value={reto.consigna} onChange={(e)=>actualizar(reto.id,{consigna:e.target.value,orden:indice+1})} /></label></article>)}</div></section>; })}
    <button className="boton-primario"><Save size={19} /> Guardar retos</button>
  </form>;
}
