import Link from "next/link";
import { ArrowLeft, Clock3, Download, ExternalLink, Play, Square, Trophy } from "lucide-react";
import { ActualizacionModeracion } from "@/components/admin/ActualizacionModeracion";
import { ReiniciarActividad } from "@/components/admin/ReiniciarActividad";
import { cerrarActividad, publicarActividad } from "@/app/admin/(privado)/actividades/actions";

function reloj(segundos: number) { return `${Math.floor(segundos / 60).toString().padStart(2, "0")}:${(segundos % 60).toString().padStart(2, "0")}`; }

export function ModeradorJuegoCxEx({ actividad }: { actividad: {
  id: string;
  titulo: string;
  estado: string;
  resultadosJuego: { id: string; nombreEquipo: string | null; puntaje: number; segundos: number; equipo: { nombre: string }; participante: { nombre: string } }[];
} }) {
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-[var(--epm-gris-fondo)] p-4 md:p-7"><ActualizacionModeracion />
    <Link href="/admin/actividades" className="inline-flex items-center gap-2 font-extrabold text-[var(--epm-azul)]"><ArrowLeft size={18} /> Volver</Link>
    <div className="mt-4 flex flex-wrap items-end justify-between gap-3"><div><p className="font-extrabold text-[var(--epm-verde-medio)]">Control del juego</p><h1 className="text-3xl font-extrabold text-[var(--epm-azul-profundo)]">{actividad.titulo}</h1></div><span className={`rounded-full px-4 py-2 text-sm font-extrabold ${actividad.estado === "PUBLICADA" ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700"}`}>{actividad.estado === "PUBLICADA" ? "Publicada" : actividad.estado === "CERRADA" ? "Cerrada" : "Borrador"}</span></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_320px]">
      <section className="marca-gradiente rounded-3xl p-7 text-white shadow-xl"><p className="font-extrabold text-[var(--epm-verde)]">Juego de 20 minutos · 60 puntos</p><h2 className="mt-2 text-3xl font-extrabold">Pago debitado, pero no aplicado</h2><p className="mt-3 max-w-4xl text-lg text-white/85">Los equipos reconstruyen el viaje, conectan CX con EX, identifican causas, eligen una solución y comprueban su doble impacto.</p><div className="mt-6 flex flex-wrap gap-3">{actividad.estado !== "PUBLICADA" ? <form action={publicarActividad}><input type="hidden" name="id" value={actividad.id} /><button className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--epm-verde)] px-5 font-extrabold text-[var(--epm-azul-profundo)]"><Play /> Publicar juego</button></form> : <form action={cerrarActividad}><input type="hidden" name="id" value={actividad.id} /><button className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/40 px-5 font-extrabold"><Square size={18} /> Cerrar juego</button></form>}</div></section>
      <aside className="tarjeta flex flex-col items-center p-5 text-center"><h2 className="font-extrabold text-[var(--epm-azul-profundo)]">QR de acceso</h2><img src={`/api/admin/actividades/${actividad.id}/qr`} alt={`QR de ${actividad.titulo}`} className="mt-3 aspect-square w-full max-w-60 rounded-2xl border bg-white object-contain p-2" /><a href={`/api/admin/actividades/${actividad.id}/qr`} target="_blank" rel="noopener noreferrer" className="boton-secundario mt-3 w-full"><ExternalLink size={17} /> Abrir QR grande</a></aside>
    </div>
    <section className="tarjeta mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><p className="font-extrabold text-[var(--epm-verde-medio)]">Resultados en tiempo real</p><h2 className="text-2xl font-extrabold text-[var(--epm-azul-profundo)]">Clasificación de equipos</h2></div><span className="rounded-full bg-sky-50 px-4 py-2 font-extrabold text-[var(--epm-azul)]">{actividad.resultadosJuego.length} equipos</span></div>
      {actividad.resultadosJuego.length ? <div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{actividad.resultadosJuego.map((item, indice) => <article key={item.id} className={`rounded-2xl border p-5 ${indice === 0 ? "border-amber-300 bg-amber-50" : "border-slate-200"}`}><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-white text-xl font-extrabold text-[var(--epm-azul)]">{indice + 1}</span>{indice === 0 && <Trophy className="text-amber-600" />}</div><h3 className="mt-4 text-xl font-extrabold text-[var(--epm-azul-profundo)]">{item.equipo.nombre}</h3>{item.nombreEquipo && <p className="text-sm text-slate-600">{item.nombreEquipo}</p>}<div className="mt-4 flex items-end justify-between"><strong className="text-4xl text-[var(--epm-azul)]">{item.puntaje}<small className="text-base">/60</small></strong><span className="flex items-center gap-1 text-sm font-bold text-slate-500"><Clock3 size={16} /> {reloj(item.segundos)}</span></div><small className="mt-3 block text-slate-400">Registró: {item.participante.nombre}</small></article>)}</div> : <p className="p-8 text-center text-slate-500">La clasificación aparecerá cuando termine el primer equipo.</p>}
    </section>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_320px]"><section className="tarjeta p-5"><h2 className="text-xl font-extrabold text-[var(--epm-azul-profundo)]">Guía para la conversación</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-slate-700"><li>Journey: canal, débito, no aplicación, contacto y cobro posterior.</li><li>Conexiones: relacionar cada síntoma del cliente con una restricción operativa.</li><li>Causas: integración, conciliación, trazabilidad y gobierno del caso.</li><li>Solución: trazabilidad integrada, alertas, protección provisional y responsable con tiempo de solución.</li><li>Cierre: distinguir lo que exige diseño de interfaz de lo que exige rediseño operativo.</li></ol></section><aside className="tarjeta p-5"><a href={`/api/admin/actividades/${actividad.id}/resultados`} className="boton-secundario mb-4 w-full"><Download size={18} /> Exportar Excel</a><p className="mb-3 text-sm text-slate-600"><strong>Exporta primero los resultados.</strong> Reiniciar libera los equipos para una nueva ronda.</p><ReiniciarActividad id={actividad.id} /></aside></div>
  </div>;
}
