import Link from "next/link";
import { ArrowLeft, Download, ExternalLink, Orbit, Play, Radio, Sparkles, Square, Users } from "lucide-react";
import { ActualizacionModeracion } from "@/components/admin/ActualizacionModeracion";
import { ReiniciarActividad } from "@/components/admin/ReiniciarActividad";
import { cerrarActividad, publicarActividad } from "@/app/admin/(privado)/actividades/actions";
import { CONSTELACIONES_UNIVERSO, type ConstelacionUniverso, type TarjetaUniverso } from "@/lib/universo-experiencia";

type MisionModeracion = {
  id: string;
  participanteId: string;
  participante: string;
  reflexion: string;
  respondidaEn: string;
  tarjeta: TarjetaUniverso;
  constelacion: ConstelacionUniverso;
};

export function ModeradorUniverso({ actividad, misiones }: { actividad: { id: string; titulo: string; estado: string; anonima: boolean }; misiones: MisionModeracion[] }) {
  const personas = new Set(misiones.map((mision) => mision.participanteId)).size;
  const recientes = [...misiones].reverse().slice(0, 9);
  const nodos = [...misiones].reverse().slice(0, 24);
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-[#04112a] text-white"><ActualizacionModeracion />
    <div aria-hidden="true" className="pointer-events-none fixed inset-0 overflow-hidden opacity-70">{Array.from({ length: 70 }, (_, indice) => <i key={indice} className="absolute rounded-full bg-white" style={{ left: `${(indice * 41 + 7) % 99}%`, top: `${(indice * 59 + 13) % 97}%`, width: 1 + indice % 3, height: 1 + indice % 3, opacity: .12 + (indice % 5) * .1, boxShadow: "0 0 9px white" }} />)}<span className="absolute -right-40 -top-52 h-[620px] w-[620px] rounded-full border-[70px] border-emerald-400/10 bg-cyan-500/5" /><span className="absolute -bottom-52 -left-36 h-[500px] w-[500px] rounded-full border-[50px] border-fuchsia-400/10" /></div>
    <main className="relative mx-auto max-w-[1500px] p-4 md:p-7">
      <div className="flex flex-wrap items-center justify-between gap-4"><Link href="/admin/actividades" className="inline-flex items-center gap-2 font-extrabold text-cyan-100/75"><ArrowLeft size={18} /> Volver</Link><span className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-extrabold ${actividad.estado === "PUBLICADA" ? "border-lime-300/30 bg-lime-300/10 text-lime-200" : "border-white/15 bg-white/10 text-white/70"}`}><Radio size={16} />{actividad.estado === "PUBLICADA" ? "Universo en vivo" : actividad.estado === "CERRADA" ? "Universo cerrado" : "Borrador"}</span></div>
      <header className="mt-5 flex flex-wrap items-end justify-between gap-5"><div><p className="font-extrabold uppercase tracking-[.22em] text-lime-300">Control orbital en vivo</p><h1 className="mt-2 font-display text-[clamp(34px,5vw,62px)] font-extrabold leading-none">{actividad.titulo}</h1><p className="mt-3 max-w-3xl text-lg text-cyan-50/60">Cada respuesta enciende un planeta. Las órbitas se pintan con el color de su constelación.</p></div><div className="flex flex-wrap gap-3">{actividad.estado !== "PUBLICADA" ? <form action={publicarActividad}><input type="hidden" name="id" value={actividad.id} /><button className="inline-flex min-h-12 items-center gap-2 rounded-full bg-lime-300 px-5 font-extrabold text-[#082343]"><Play /> Abrir universo</button></form> : <form action={cerrarActividad}><input type="hidden" name="id" value={actividad.id} /><button className="inline-flex min-h-12 items-center gap-2 rounded-full border border-white/30 bg-white/5 px-5 font-extrabold"><Square size={18} /> Cerrar actividad</button></form>}</div></header>

      <div className="mt-7 grid gap-5 xl:grid-cols-[1fr_300px]">
        <section className="relative min-h-[610px] overflow-hidden rounded-[2.5rem] border border-white/10 bg-[radial-gradient(circle_at_50%_50%,rgba(6,182,212,.15),transparent_48%),linear-gradient(145deg,rgba(12,42,83,.88),rgba(5,19,48,.94))] shadow-2xl">
          <div className="absolute left-5 top-5 z-20 flex flex-wrap gap-2"><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-extrabold backdrop-blur"><Sparkles className="mr-2 inline text-lime-300" size={17} />{misiones.length} misiones</span><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-extrabold backdrop-blur"><Users className="mr-2 inline text-cyan-300" size={17} />{personas} participantes</span></div>
          <div className="absolute inset-0">
            {CONSTELACIONES_UNIVERSO.map((constelacion, indice) => {
              const cantidad = misiones.filter((mision) => mision.constelacion.id === constelacion.id).length;
              const ancho = 88 - indice * 13;
              return <span key={constelacion.id} className="absolute left-1/2 top-1/2 rounded-[50%] border-2 transition-all duration-700" style={{ width: `${ancho}%`, height: `${ancho * .55}%`, transform: `translate(-50%,-50%) rotate(${indice % 2 ? 11 : -11}deg)`, borderColor: cantidad ? constelacion.colorSecundario : "rgba(255,255,255,.08)", opacity: cantidad ? Math.min(.95, .36 + cantidad * .06) : .45, boxShadow: cantidad ? `0 0 ${18 + cantidad * 3}px ${constelacion.color}55, inset 0 0 24px ${constelacion.color}20` : "none" }} />;
            })}
            <span className="absolute left-1/2 top-1/2 grid h-40 w-40 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-[radial-gradient(circle_at_32%_25%,#ecfccb,#84cc16_22%,#078a98_60%,#071b3c)] text-center shadow-[0_0_90px_rgba(132,204,22,.3)]"><span><Orbit className="mx-auto" size={35} /><strong className="mt-1 block font-display text-4xl">{misiones.length}</strong><small className="font-extrabold uppercase tracking-widest text-white/70">en órbita</small></span></span>
            {nodos.map((mision, indice) => { const angulo = indice / Math.max(nodos.length, 1) * Math.PI * 2 - Math.PI / 2; const pista = indice % 5; const radioX = 42 - pista * 6.2; const radioY = 28 - pista * 3.5; return <span key={mision.id} title={`${mision.participante}: ${mision.tarjeta.titulo}`} className="absolute grid h-9 w-9 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white/45 text-xs font-extrabold shadow-xl transition-all duration-700" style={{ left: `${50 + Math.cos(angulo) * radioX}%`, top: `${50 + Math.sin(angulo) * radioY}%`, background: mision.constelacion.color, boxShadow: `0 0 25px ${mision.constelacion.colorSecundario}` }}>{Math.max(1, misiones.length - indice)}</span>; })}
          </div>
          {!misiones.length && <div className="absolute bottom-12 left-1/2 w-full -translate-x-1/2 px-6 text-center text-cyan-50/55"><p className="font-display text-xl font-extrabold text-white/75">Esperando la primera señal…</p><p className="mt-2">El universo se iluminará automáticamente cuando alguien responda.</p></div>}
        </section>
        <aside className="rounded-[2rem] border border-white/10 bg-white/[.07] p-5 text-center backdrop-blur"><h2 className="font-display text-xl font-extrabold">Portal de acceso</h2><img src={`/api/admin/actividades/${actividad.id}/qr`} alt={`QR de ${actividad.titulo}`} className="mx-auto mt-4 aspect-square w-full max-w-60 rounded-2xl bg-white object-contain p-2" /><a href={`/api/admin/actividades/${actividad.id}/qr`} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-full border border-white/25 px-4 py-3 font-extrabold"><ExternalLink size={17} /> Abrir QR grande</a><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-cyan-300/10 p-4"><strong className="block text-3xl text-cyan-200">{personas}</strong><small className="text-white/55">personas</small></div><div className="rounded-2xl bg-lime-300/10 p-4"><strong className="block text-3xl text-lime-200">{misiones.length}</strong><small className="text-white/55">tarjetas</small></div></div></aside>
      </div>

      <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[.06] p-5 backdrop-blur md:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-extrabold uppercase tracking-[.18em] text-lime-300">Señales recibidas</p><h2 className="mt-1 font-display text-3xl font-extrabold">Lo que está ocurriendo</h2></div><div className="flex gap-2"><a href={`/api/admin/actividades/${actividad.id}/resultados`} className="inline-flex items-center gap-2 rounded-full border border-white/25 px-4 py-2 font-extrabold"><Download size={18} /> Excel</a></div></div>
        {recientes.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{recientes.map((mision) => <article key={mision.id} className="relative overflow-hidden rounded-3xl border p-5" style={{ borderColor: `${mision.constelacion.colorSecundario}66`, background: `linear-gradient(145deg,${mision.constelacion.color}36,rgba(255,255,255,.04))` }}><span className="absolute -right-8 -top-8 h-24 w-24 rounded-full border-[12px] border-white/5" /><div className="relative flex items-center justify-between gap-3"><span className="text-xs font-extrabold uppercase tracking-[.15em]" style={{ color: mision.constelacion.colorSecundario }}>{mision.constelacion.nombre}</span><span className="h-3 w-3 rounded-full" style={{ background: mision.constelacion.colorSecundario, boxShadow: `0 0 15px ${mision.constelacion.colorSecundario}` }} /></div><h3 className="relative mt-3 font-display text-xl font-extrabold">{mision.tarjeta.titulo}</h3><p className="relative mt-3 line-clamp-3 text-sm leading-relaxed text-white/72">“{mision.reflexion}”</p><p className="relative mt-4 text-xs font-bold text-white/45">{actividad.anonima ? "Participante anónimo" : mision.participante}</p></article>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-white/15 p-8 text-center text-white/50">Las tarjetas y reflexiones aparecerán aquí en tiempo real.</p>}
      </section>
      <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_320px]"><section className="rounded-[2rem] border border-white/10 bg-white/[.06] p-5"><h2 className="font-display text-xl font-extrabold">Constelaciones activadas</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{CONSTELACIONES_UNIVERSO.map((constelacion) => { const cantidad = misiones.filter((mision) => mision.constelacion.id === constelacion.id).length; return <div key={constelacion.id} className="rounded-2xl border border-white/10 p-4" style={{ background: `${constelacion.color}20` }}><span className="block h-2 rounded-full" style={{ background: cantidad ? constelacion.colorSecundario : "rgba(255,255,255,.12)", boxShadow: cantidad ? `0 0 15px ${constelacion.color}` : "none" }} /><strong className="mt-3 block">{constelacion.nombre}</strong><small className="text-white/50">{cantidad} {cantidad === 1 ? "misión" : "misiones"}</small></div>; })}</div></section><aside className="rounded-[2rem] border border-white/10 bg-white/[.06] p-5"><p className="mb-3 text-sm text-white/55"><strong className="text-white/80">Exporta primero los resultados.</strong> Reiniciar elimina las órbitas, respuestas y puntos de esta actividad.</p><div className="[&_button]:border-white/25 [&_button]:text-white"><ReiniciarActividad id={actividad.id} /></div></aside></div>
    </main>
  </div>;
}
